In [1]:
import pandas as pd

In [3]:
info = {
    "Name" : ["Amit", "Golu", "Monu"],
    "CGPA" : [9.0, 8.5, 8.7]        
}

df = pd.DataFrame(info)
print(df)

   Name  CGPA
0  Amit   9.0
1  Golu   8.5
2  Monu   8.7

In [ ]:
sr = pd.Series([2, 4, 6, 8, 10])
print(sr)
print(type(sr))
print(sr[0])

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
2

In [8]:
s = pd.Series([18, 20, 22, 26, 28], index=["Adam", "Amit", "Golu", "Sem", "Nope"])
print(s)

print(s[0]) #index based
print(s["Adam"]) #label based

Adam    18
Amit    20
Golu    22
Sem     26
Nope    28
dtype: int64
18
18

/tmp/ipykernel_47539/492199073.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0]) #index based

In [10]:
s1 = pd.Series([18, 20, 22, 26, 28])
s2 = pd.Series([18, 20, 22, 26, 28])

print(s1+s2)

new_s1 = s1.drop(0)
print(s1)
print(new_s1)

0    36
1    40
2    44
3    52
4    56
dtype: int64
0    18
1    20
2    22
3    26
4    28
dtype: int64
1    20
2    22
3    26
4    28
dtype: int64

In [12]:
info = {
    "Name" : ["Amit", "Golu", "Monu"],
    "CGPA" : [9.0, 8.5, 8.7],
    "Age" : [18, 20, 22]
}

df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

   Name  CGPA  Age
0  Amit   9.0   18
1  Golu   8.5   20
2  Monu   8.7   22
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'CGPA', 'Age'], dtype='object')

In [13]:
df1 = pd.DataFrame([["Alice", 23], ["Bob", 24], ["Eve", 25]], columns = ["Name", "Age"])
print(df1)

    Name  Age
0  Alice   23
1    Bob   24
2    Eve   25

In [ ]:
import numpy as np
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
df2 = pd.DataFrame(np_arr, columns = ["a", "b", "c"])
print(df2)

   a  b  c
0  1  2  3
1  4  5  6

In [4]:
pd.read_csv("emp_data.csv")

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [7]:
df = pd.read_json("emp_data.json")

In [19]:
df.head() # print starting 5 row
df.tail() # last 5 value
df.tail(2) # last 2 row
df.sample()  # any random
df.info()   # info about data
df.shape   
df.describe()  # all basic calc like avg, ...
df.nunique()  # number of unique

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [3]:
df = pd.read_csv("globalAirQuality.csv")

In [18]:
df.sample()
df.describe()
df[["city", "aqi"]]
df["country"]

df.loc[0] # location or position based
df.loc[0:2]  # inclusive
df.iloc[1] # index
df.iloc[0:2]  # not inclusive

#cells -> row, col
df.loc[0, "aqi"]
df.loc[0:2, ["city", "aqi"]]
df.iloc[0:2, 2:4]

df.at[0, "city"]
df.iat[0, 1]


vw = df["city"]  #view -> changes reflect in original
cp = df["city"].copy()  #copy

'US'

In [37]:
# filtering of data
df[ df["aqi"] > 100]
df[ (df["aqi"] > 100) & (df["temperature"] > 30)]

df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]

temp = df[ (df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]
temp.iloc[0]

#Query method  -> copy
df.query("aqi > 200 & temperature > 3")

aqi_val = 180
df.query("aqi > @aqi_val & temperature > 3")[["city", "aqi"]]

              city  aqi
112       New York  192
589    Los Angeles  189
745         London  214
1154         Paris  187
1455        Berlin  182
...            ...  ...
17458     Helsinki  202
17529     Helsinki  231
17815       Zurich  203
17885       Zurich  190
17886       Zurich  185

[79 rows x 2 columns]

In [60]:
# Cleaning 

df = pd.read_csv("raw_data.csv")

In [61]:
df
df.isnull()
df.isna()

df.isnull().sum()  # giv esum of all null col

df.dropna()  # drop all the null value 
df.dropna(axis=1) # col drop

df.fillna("nhi")
df.fillna(df["age"].mean())

df.ffill() # forward fill
df.bfill() # backward fill

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   3    Jane Smith  34.0  Canada   Female  62000.0
3   4          Alex  34.0     USA  Unknown  47000.0
4   5  Maria Garcia  34.0   Spain   Female  51000.0
5   6        Li Wei  27.0   China     Male  51000.0
6   7    Ahmed Khan  45.0   India   Female  73000.0
7   8    Rachel Lee  29.0     USA   Female  68000.0
8   9   Carlos Ruiz  31.0  Mexico     Male  62000.0
9  10   Emily Davis  31.0     USA    45000      NaN

In [65]:
# Handle duplicate
df.duplicated()
df["country"].duplicated()

df2 = df.copy()

df.drop_duplicates(inplace=True)
df

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
2   3    Jane Smith   NaN  Canada   Female  62000.0
3   4          Alex   NaN     USA  Unknown  47000.0
4   5  Maria Garcia  34.0   Spain   Female      NaN
5   6        Li Wei  27.0   China     Male  51000.0
6   7    Ahmed Khan  45.0   India   Female  73000.0
7   8    Rachel Lee  29.0     USA   Female  68000.0
8   9   Carlos Ruiz   NaN  Mexico     Male  62000.0
9  10   Emily Davis  31.0     USA    45000      NaN

In [74]:
df.dtypes
df2 = df.copy()
df2 = df2.fillna(0)
df2 = df2["age"].astype("int64")
df2.dtypes

dtype('int64')

In [79]:
dt = pd.to_datetime("2026-02-26")
dt

type(dt)

pandas._libs.tslibs.timestamps.Timestamp

In [92]:
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

df["name"].str.split(" ")

df["country"].str.contains("US")
df["country"].str.contains("india", case=False)

0    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: country, dtype: bool